// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mq2VSAZdgvM5FmVUmcY3kVW3YobV50g',
    appId: '1:1045486457827:web:8c0401e00f840cad5c46d6',
    messagingSenderId: '1045486457827',
    projectId: 'optidocs-1a176',
    authDomain: 'optidocs-1a176.firebaseapp.com',
    storageBucket: 'optidocs-1a176.firebasestorage.app',
    measurementId: 'G-MFFZ1EPL6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4OQ-bBakjCP-yWSWAryNe5Mfr5RaF4I',
    appId: '1:1045486457827:android:53ab22df858bc8775c46d6',
    messagingSenderId: '1045486457827',
    projectId: 'optidocs-1a176',
    storageBucket: 'optidocs-1a176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vo9d12FYdXXSXg_KvSFPQ8Hzwfe-2mY',
    appId: '1:1045486457827:ios:8b3bddf2480f5d805c46d6',
    messagingSenderId: '1045486457827',
    projectId: 'optidocs-1a176',
    storageBucket: 'optidocs-1a176.firebasestorage.app',
    iosBundleId: 'com.example.optidocsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vo9d12FYdXXSXg_KvSFPQ8Hzwfe-2mY',
    appId: '1:1045486457827:ios:8b3bddf2480f5d805c46d6',
    messagingSenderId: '1045486457827',
    projectId: 'optidocs-1a176',
    storageBucket: 'optidocs-1a176.firebasestorage.app',
    iosBundleId: 'com.example.optidocsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4mq2VSAZdgvM5FmVUmcY3kVW3YobV50g',
    appId: '1:1045486457827:web:7fd05d0fb997b14a5c46d6',
    messagingSenderId: '1045486457827',
    projectId: 'optidocs-1a176',
    authDomain: 'optidocs-1a176.firebaseapp.com',
    storageBucket: 'optidocs-1a176.firebasestorage.app',
    measurementId: 'G-4G44V248Q2',
  );
}
